# Generated by Django 2.2.16 on 2022-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Впишите текст здесь', verbose_name='Текст комментария'),
        ),
    ]
