# Generated by Django 2.2.16 on 2022-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220326_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Впишите текст здесь', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(help_text='Введите текст поста', max_length=200),
        ),
    ]
