# Generated by Django 2.2.16 on 2022-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220328_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(help_text='Введите текст поста', max_length=200, verbose_name='Текст поста'),
        ),
    ]
