# Generated by Django 2.2.16 on 2022-03-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220328_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
